# Cannibalization analysis with Markov process and eigenvalues 

In [30]:
import sys
sys.path.append('D:/source/repos')
from utilities.std_imports import *
from sklearn.preprocessing import MinMaxScaler

### Data generation
Proportion of canibalization of products A, B, C after 1 month. s0 initial monthly demand

In [53]:
C = np.array([[0.8, 0.1, 0.1], [0.03, 0.95, 0.02], [0.2, 0.05, 0.75]])
d0 = np.array([30, 15, 55])
pd.DataFrame(data=C, columns=['A', 'B', 'C'], index=['A', 'B', 'C'])

A     B     C
A  0.80  0.10  0.10
B  0.03  0.95  0.02
C  0.20  0.05  0.75

### Demand calculation for n periods

After 1,2,3 months

In [52]:
d1 = np.matmul(C, d0)
d2 = np.matmul(C, d1)
d1, d2

(array([[31.  ],
        [16.25],
        [48.  ]]),
 array([[31.225 ],
        [17.3275],
        [43.0125]]))

### Steady state : eigenvalues

In [47]:
st = [1,1,1]
ev = np.linalg.eig(C)[0]
ev/ev.sum() * 100

array([25.26713617, 34.73286383, 40.        ])

### Credits & Links

https://www.intmath.com/matrices-determinants/8-applications-eigenvalues-eigenvectors.php